version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Image
          command: docker build -t appvia/kube-toolset:$CIRCLE_SHA1 .
  push_latest:
    machine: true
    steps:
      - checkout
      - run:
          name: Push to Quay with tag latest
          command: |
            docker build -t quay.io/appvia/kube-toolset:latest .
            docker login quay.io --username $QUAY_USERNAME --password $QUAY_PASSWORD
            docker push quay.io/appvia/kube-toolset:latest
  push_tag:
    machine: true
    steps:
      - checkout
      - run:
          name: Push to Quay with Git tag
          command: |
            docker build -t quay.io/appvia/kube-toolset:$CIRCLE_TAG .
            docker login quay.io --username $QUAY_USERNAME --password $QUAY_PASSWORD
            docker push quay.io/appvia/kube-toolset:$CIRCLE_TAG
workflows:
  version: 2
  build_and_upload_latest:
    jobs:
      - build
      - push_latest:
          requires:
            - build
          filters:
            branches:
              only:
                - master
            tags:
              ignore: /.*/
  build_and_upload_tag:
    jobs:
      - push_tag:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
